[package]
name = "trade-city"
version = "0.1.0"
authors = ["Jan Baumann"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
rust_decimal = "1.16"
rust_decimal_macros = "1.16"
